class CalendarEvent {
  const CalendarEvent({
    required this.date,
    required this.region,
    required this.nearbyUniversities,
    required this.lectureWindow,
    required this.courseAlignment,
  });

  final String date;
  final String region;
  final String nearbyUniversities;
  final String lectureWindow;
  final String courseAlignment;
}

class SpeakerProfile {
  const SpeakerProfile({
    required this.name,
    required this.boardRole,
    required this.metroRegion,
    required this.company,
    required this.title,
    required this.expertiseTags,
  });

  final String name;
  final String boardRole;
  final String metroRegion;
  final String company;
  final String title;
  final String expertiseTags;
}

class CampusContact {
  const CampusContact({
    required this.program,
    required this.category,
    required this.recurrence,
    required this.hostUnit,
    required this.volunteerRoles,
    required this.audience,
    required this.publicUrl,
    required this.contactName,
    required this.contactInfo,
  });

  final String program;
  final String category;
  final String recurrence;
  final String hostUnit;
  final String volunteerRoles;
  final String audience;
  final String publicUrl;
  final String contactName;
  final String contactInfo;
}

class CourseScheduleItem {
  const CourseScheduleItem({
    required this.instructor,
    required this.course,
    required this.section,
    required this.title,
    required this.days,
    required this.startTime,
    required this.endTime,
    required this.enrollmentCap,
    required this.mode,
    required this.guestLectureFit,
  });

  final String instructor;
  final String course;
  final String section;
  final String title;
  final String days;
  final String startTime;
  final String endTime;
  final String enrollmentCap;
  final String mode;
  final String guestLectureFit;
}

const calendarEvents = [
  CalendarEvent(
    date: '2026-04-16',
    region: 'Portland',
    nearbyUniversities: 'Portland State, U of Oregon, Oregon State',
    lectureWindow: 'Apr 7–14 (Week 11 Spring)',
    courseAlignment: 'Marketing Research, Consumer Behavior',
  ),
  CalendarEvent(
    date: '2026-05-14',
    region: 'San Diego',
    nearbyUniversities: 'SDSU, USD, UC San Diego',
    lectureWindow: 'May 5–12 (Finals prep)',
    courseAlignment: 'Analytics capstones, project presentations',
  ),
  CalendarEvent(
    date: '2026-06-18',
    region: 'Los Angeles',
    nearbyUniversities: 'UCLA, USC, Cal Poly Pomona, LMU',
    lectureWindow: 'Jun 9–16 (Summer session start)',
    courseAlignment: 'Summer intensives, boot camps',
  ),
  CalendarEvent(
    date: '2026-07-23',
    region: 'San Francisco',
    nearbyUniversities: 'USF, SFSU, Berkeley Haas, Santa Clara',
    lectureWindow: 'Jul 14–21 (Summer session)',
    courseAlignment: 'Executive education, certificate programs',
  ),
  CalendarEvent(
    date: '2026-08-20',
    region: 'Seattle',
    nearbyUniversities: 'UW Foster, Seattle U, WSU',
    lectureWindow: 'Aug 11–18 (Pre-fall orientation)',
    courseAlignment: 'New student orientations, welcome week',
  ),
  CalendarEvent(
    date: '2026-09-10',
    region: 'Ventura / Thousand Oaks',
    nearbyUniversities: 'CLU, CSUCI',
    lectureWindow: 'Sep 1–8 (Week 2 Fall)',
    courseAlignment: 'Intro courses — cast the widest net',
  ),
  CalendarEvent(
    date: '2026-10-15',
    region: 'Orange County / Long Beach',
    nearbyUniversities: 'CSULB, Chapman, UCI, CSUF',
    lectureWindow: 'Oct 6–13 (Week 5–6 Fall)',
    courseAlignment: 'Mid-term guest lecture sweet spot',
  ),
  CalendarEvent(
    date: '2026-12-03',
    region: 'Seattle',
    nearbyUniversities: 'UW, Seattle U',
    lectureWindow: 'Nov 24–Dec 1 (Week 10 Fall)',
    courseAlignment: 'Capstone presentations, career panels',
  ),
  CalendarEvent(
    date: '2026-12-10',
    region: 'Los Angeles',
    nearbyUniversities: 'UCLA, USC, CPP, LMU',
    lectureWindow: 'Dec 1–8 (Last week of classes)',
    courseAlignment: 'What\'s next career-focused sessions',
  ),
];

const speakerProfiles = [
  SpeakerProfile(
    name: 'Travis Miller',
    boardRole: 'President',
    metroRegion: 'Ventura / Thousand Oaks',
    company: 'PureSpectrum',
    title: 'SVP, Sales & Client Development',
    expertiseTags: 'data collection, MR technology adoption, sales, innovation',
  ),
  SpeakerProfile(
    name: 'Amanda Keller-Grill',
    boardRole: 'President Elect',
    metroRegion: 'Los Angeles — West',
    company: 'InnovateMR',
    title: 'SVP, Global Quality & Research Excellence',
    expertiseTags:
        'research quality, recruitment, delivery, client retention, operations',
  ),
  SpeakerProfile(
    name: 'Katrina Noelle',
    boardRole: 'Treasurer Elect',
    metroRegion: 'San Francisco',
    company: 'KNow Research / Scoot Insights',
    title: 'Founder & CEO',
    expertiseTags:
        'qualitative research, custom research design, decision-making methodology, mentorship, DEI',
  ),
  SpeakerProfile(
    name: 'Rob Kaiser',
    boardRole: 'Treasurer',
    metroRegion: 'Los Angeles — Long Beach',
    company: 'PSB',
    title: 'Marketing Science Leader',
    expertiseTags:
        'AI innovation, creative analytics, marketing science, brand research',
  ),
  SpeakerProfile(
    name: 'Donna Flynn',
    boardRole: 'Secretary',
    metroRegion: 'Los Angeles',
    company: 'Sago',
    title: 'Facility Operations & Project Execution Lead',
    expertiseTags:
        'project management, recruiting, on-site methodologies, clinical research, qualitative ops',
  ),
  SpeakerProfile(
    name: 'Greg Carter',
    boardRole: 'Metro Director — Seattle',
    metroRegion: 'Seattle',
    company: 'Carter Research & Consulting',
    title: 'Principal',
    expertiseTags:
        'focus groups, depth interviews, quantitative research, 40 yrs experience',
  ),
  SpeakerProfile(
    name: 'Katie Nelson',
    boardRole: 'Metro Director — Portland',
    metroRegion: 'Portland',
    company: 'KashKick',
    title: 'Survey & Shopping Verticals Lead',
    expertiseTags:
        'brand strategy, optimization, partner relationships, member engagement',
  ),
  SpeakerProfile(
    name: 'Liz O\'Hara',
    boardRole: 'Metro Director — San Francisco',
    metroRegion: 'San Francisco',
    company: 'Abbott (Global Market Insights)',
    title: 'Insights Strategy & Innovation Lead',
    expertiseTags:
        'medical devices, diabetes portfolio, analytics, AI tools, global insights',
  ),
  SpeakerProfile(
    name: 'Sean McKenna',
    boardRole: 'Metro Director — San Diego',
    metroRegion: 'San Diego',
    company: '(prev. Luth, Toluna)',
    title: 'Sales',
    expertiseTags: 'sales, client development, industry networking',
  ),
  SpeakerProfile(
    name: 'Calvin Friesth',
    boardRole: 'Metro Director — Los Angeles',
    metroRegion: 'Los Angeles',
    company: '(consultative client development)',
    title: 'Client Development Leader',
    expertiseTags:
        'client development, insights industry events, 15+ yrs experience',
  ),
  SpeakerProfile(
    name: 'Ashley Le Blanc',
    boardRole: 'Director of Communications',
    metroRegion: 'Los Angeles — North',
    company: 'Fieldwork',
    title: 'Director of Communications',
    expertiseTags:
        'brand strategy, narrative development, digital transformation, multi-channel content, qualitative research',
  ),
  SpeakerProfile(
    name: 'Monica Voss',
    boardRole: 'Director of Partnerships',
    metroRegion: 'San Diego',
    company: 'MarketCast',
    title: 'VP, Client Success',
    expertiseTags:
        'tech/telecom/platforms verticals, data-driven storytelling, SaaS, client development, analytics',
  ),
  SpeakerProfile(
    name: 'Molly Strawn',
    boardRole: 'Co-Director of Membership',
    metroRegion: 'Los Angeles — North',
    company: 'aytm',
    title: 'Senior Growth Marketing Manager',
    expertiseTags: 'growth marketing, market research, client services',
  ),
  SpeakerProfile(
    name: 'Shana DeMarinis',
    boardRole: 'Co-Director of Membership',
    metroRegion: 'Ventura / Thousand Oaks',
    company: 'TestSet',
    title: 'SVP, Customer Experience',
    expertiseTags: 'customer experience, market research, 13 yrs experience',
  ),
  SpeakerProfile(
    name: 'Dr. Yufan Lin',
    boardRole: 'Director of New Professionals',
    metroRegion: 'Los Angeles — East',
    company: 'Cal Poly Pomona',
    title: 'Assistant Professor of Marketing',
    expertiseTags:
        'econometrics, generative AI, marketing research, sales technology, Harvard Business Cases',
  ),
  SpeakerProfile(
    name: 'Adam Portner',
    boardRole: 'Director of Regional Engagement',
    metroRegion: 'San Francisco',
    company: '(prev. RealityMine, Prodege, Dynata, Metrixlab, Circana)',
    title: 'Insights Leader',
    expertiseTags: 'sales, client services, operations, 25+ yrs experience',
  ),
  SpeakerProfile(
    name: 'Laurie Bae',
    boardRole: 'Director of Events',
    metroRegion: 'San Francisco',
    company: 'Ipsos',
    title: 'Strategic Growth Team',
    expertiseTags: 'event management, strategic growth',
  ),
  SpeakerProfile(
    name: 'Amber Jawaid',
    boardRole: 'Director of Inclusion & Diversity',
    metroRegion: 'Los Angeles',
    company: '(senior MR leader)',
    title: 'Senior Market Research Leader',
    expertiseTags:
        'innovation, strategic planning, diversity & inclusion, customer understanding, 20+ yrs experience',
  ),
];

const campusContacts = [
  CampusContact(
    program: 'AI for a Better Future Hackathon',
    category: 'AI / Hackathon',
    recurrence: 'Annual',
    hostUnit: 'College of Business / Mitchell C. Hill Center',
    volunteerRoles: 'Judge; Mentor; Guest speaker',
    audience: 'Students (business/tech)',
    publicUrl:
        'https://www.cpp.edu/cba/digital-innovation/what-we-do/ai-hackathon.shtml',
    contactName: 'Mitchell C. Hill Center (general contact)',
    contactInfo: 'mhcenter@cpp.edu',
  ),
  CampusContact(
    program: 'AI Hackathon (CPP hub page)',
    category: 'AI / Hackathon',
    recurrence: 'Annual',
    hostUnit: 'Cal Poly Pomona (event portal)',
    volunteerRoles: 'Judge; Mentor; Guest speaker',
    audience: 'Students',
    publicUrl: 'https://www.cpp.edu/cba/ai-hackathon/index.shtml',
    contactName: 'See hub page for current routing/contact',
    contactInfo: 'See page',
  ),
  CampusContact(
    program: 'Information Technology Competition (ITC)',
    category: 'Case competition',
    recurrence: 'Annual',
    hostUnit: 'MISSA (student org)',
    volunteerRoles: 'Judge; Mentor; Guest speaker',
    audience: 'MIS/IS, analytics, business students',
    publicUrl: 'https://www.calpolymissa.org/ITC.html',
    contactName: 'Wesley Lin & Matthew Kwan (ITC Directors)',
    contactInfo: 'itcchairs@calpolymissa.org',
  ),
  CampusContact(
    program: 'Bronco Startup Challenge (SIIL)',
    category: 'Entrepreneurship / Pitch',
    recurrence: 'Ongoing series + pitch events',
    hostUnit: 'Student Innovation Idea Labs (SIIL)',
    volunteerRoles: 'Judge; Mentor; Workshop speaker',
    audience: 'Student founders / entrepreneurship students',
    publicUrl: 'https://www.cpp.edu/siil/about-us/contact-us.shtml',
    contactName: 'SIIL (general)',
    contactInfo: 'siil@cpp.edu; 909-869-3741',
  ),
  CampusContact(
    program: 'Bronco Startup Challenge (staff contact)',
    category: 'Entrepreneurship / Pitch',
    recurrence: 'Ongoing series + pitch events',
    hostUnit: 'Student Innovation Idea Labs (SIIL)',
    volunteerRoles: 'Judge; Mentor; Workshop speaker',
    audience: 'Student founders / entrepreneurship students',
    publicUrl: 'https://www.cpp.edu/siil/about-us/our-staff.shtml',
    contactName: 'Y. Olive Li (Director, SIIL)',
    contactInfo: 'yaoli@cpp.edu',
  ),
  CampusContact(
    program: 'SWIFT Tech Symposium',
    category: 'Tech symposium / Speakers',
    recurrence: 'Annual',
    hostUnit: 'SWIFT (student org)',
    volunteerRoles: 'Guest speaker; Workshop lead; Panelist',
    audience: 'Students (tech + business)',
    publicUrl: 'https://techsymposium.calpolyswift.org/',
    contactName: 'SWIFT Symposium contacts (site lists)',
    contactInfo: 'Use \'Contact SWIFT\' emails on site',
  ),
  CampusContact(
    program: 'BroncoHacks',
    category: 'Hackathon',
    recurrence: 'Recurring (varies by year)',
    hostUnit: 'BroncoHacks (student-led)',
    volunteerRoles: 'Judge; Speaker; Volunteer',
    audience: 'Students (hackathon teams)',
    publicUrl: 'https://broncohacks.carrd.co/',
    contactName: 'BroncoHacks team (via interest forms)',
    contactInfo: 'Use \'Want to Judge?\' / \'Speaking at our Event\' links',
  ),
  CampusContact(
    program: 'OUR — RSCA Conference',
    category: 'Research showcase',
    recurrence: 'Annual (often spring)',
    hostUnit: 'Office of Undergraduate Research (OUR)',
    volunteerRoles: 'Panelist; Reviewer; Guest speaker',
    audience: 'Undergraduate researchers',
    publicUrl: 'https://www.cpp.edu/our-cpp/index.shtml',
    contactName: 'OUR (general)',
    contactInfo: 'our@cpp.edu',
  ),
  CampusContact(
    program: 'OUR — Director contact',
    category: 'Research showcase',
    recurrence: 'Annual',
    hostUnit: 'Office of Undergraduate Research (OUR)',
    volunteerRoles: 'Panelist; Reviewer; Guest speaker',
    audience: 'Undergraduate researchers',
    publicUrl: 'https://www.cpp.edu/our-cpp/about/staff.shtml',
    contactName: 'Dr. Ever Barraza (Director, OUR)',
    contactInfo: 'edbarraza@cpp.edu',
  ),
  CampusContact(
    program: 'OUR — CARS (Creative Activities & Research Symposium)',
    category: 'Research symposium',
    recurrence: 'Annual (often summer)',
    hostUnit: 'Office of Undergraduate Research (OUR)',
    volunteerRoles: 'Guest speaker; External discussant',
    audience: 'Researchers / students',
    publicUrl: 'https://www.cpp.edu/our-cpp/index.shtml',
    contactName: 'OUR (general)',
    contactInfo: 'our@cpp.edu',
  ),
  CampusContact(
    program: 'College of Science Research Symposium',
    category: 'Research symposium',
    recurrence: 'Annual',
    hostUnit: 'College of Science',
    volunteerRoles: 'Judge/Reviewer (posters); Guest speaker',
    audience: 'Science students/researchers',
    publicUrl:
        'https://www.cpp.edu/sci/events/research-symposium.shtml',
    contactName: 'College of Science (general contact)',
    contactInfo: 'sci_dean@cpp.edu (phone listed on page)',
  ),
  CampusContact(
    program: 'CPP Career Center — Employer Engagement',
    category: 'Career services',
    recurrence: 'Recurring each term/year',
    hostUnit: 'CPP Career Center',
    volunteerRoles: 'Guest speaker; Panelist; Employer event',
    audience: 'Students across majors',
    publicUrl:
        'https://careercenter.cpp.edu/employer-engagement-opportunities/',
    contactName: 'Career Center (general)',
    contactInfo: 'career@cpp.edu; 909-869-2342',
  ),
  CampusContact(
    program: 'CPP Career Center — Career Fairs',
    category: 'Career fairs',
    recurrence: 'Recurring',
    hostUnit: 'CPP Career Center',
    volunteerRoles: 'Industry panelist; Employer-side speaker',
    audience: 'Students',
    publicUrl: 'https://careercenter.cpp.edu/channels/career-fairs/',
    contactName: 'LaKisha Torrence (Employer Engagement & Events Specialist)',
    contactInfo: 'lrtorrence@cpp.edu',
  ),
  CampusContact(
    program: 'CPP Career Center — Business college coaching liaison',
    category: 'Career services',
    recurrence: 'Ongoing',
    hostUnit: 'CPP Career Center',
    volunteerRoles: 'Guest speaker for business students',
    audience: 'College of Business Administration students',
    publicUrl: 'https://careercenter.cpp.edu/staff/',
    contactName:
        'Beth Lee (Lead Career Coach, College of Business Administration)',
    contactInfo: 'bethlee@cpp.edu',
  ),
  CampusContact(
    program: 'CPP Career Center — Employer relations / on-campus recruiting',
    category: 'Career services',
    recurrence: 'Ongoing',
    hostUnit: 'CPP Career Center',
    volunteerRoles: 'Guest speaker; Recruiting/industry talks',
    audience: 'Students + employer partners',
    publicUrl: 'https://careercenter.cpp.edu/staff/',
    contactName:
        'Gerard Russo (Employer Relations & On-Campus Recruiting Specialist)',
    contactInfo: 'gjrusso@cpp.edu',
  ),
];

const courseSchedule = [
  CourseScheduleItem(
    instructor: 'Chie Ishihara',
    course: 'IBM 4121',
    section: '01',
    title: 'Intl Marketing Research',
    days: 'T',
    startTime: '5:30 PM',
    endTime: '8:15 PM',
    enrollmentCap: '30',
    mode: 'Face-to-Face',
    guestLectureFit: 'High',
  ),
  CourseScheduleItem(
    instructor: 'Megan Good',
    course: 'IBM 3302',
    section: '02',
    title: 'Marketing Research',
    days: 'T TH',
    startTime: '8:30 AM',
    endTime: '9:45 AM',
    enrollmentCap: '30',
    mode: 'Face-to-Face',
    guestLectureFit: 'High',
  ),
  CourseScheduleItem(
    instructor: 'Yufan Lin',
    course: 'IBM 3302',
    section: '03',
    title: 'Marketing Research',
    days: 'T',
    startTime: '2:30 PM',
    endTime: '3:45 PM',
    enrollmentCap: '30',
    mode: 'Hybrid Sync',
    guestLectureFit: 'High',
  ),
  CourseScheduleItem(
    instructor: 'Yufan Lin',
    course: 'GBA 6520',
    section: '02',
    title: 'Marketing Mgmt Applications',
    days: 'T',
    startTime: '7:00 PM',
    endTime: '9:45 PM',
    enrollmentCap: '45',
    mode: 'Hybrid Sync',
    guestLectureFit: 'High',
  ),
  CourseScheduleItem(
    instructor: 'Maha Ghosn',
    course: 'GBA 6830',
    section: '01',
    title: 'Business Research Methods',
    days: 'TH',
    startTime: '7:00 PM',
    endTime: '9:45 PM',
    enrollmentCap: '45',
    mode: 'Hybrid Async',
    guestLectureFit: 'High',
  ),
  CourseScheduleItem(
    instructor: 'Maha Ghosn',
    course: 'IBM 3202',
    section: '03',
    title: 'Market Analysis and Control',
    days: 'T',
    startTime: '2:30 PM',
    endTime: '3:45 PM',
    enrollmentCap: '30',
    mode: 'Hybrid Sync',
    guestLectureFit: 'High',
  ),
  CourseScheduleItem(
    instructor: 'Maha Ghosn',
    course: 'IBM 3202',
    section: '04',
    title: 'Market Analysis and Control',
    days: 'T',
    startTime: '4:00 PM',
    endTime: '5:15 PM',
    enrollmentCap: '30',
    mode: 'Hybrid Sync',
    guestLectureFit: 'High',
  ),
  CourseScheduleItem(
    instructor: 'Olga Di Franco',
    course: 'IBM 4112',
    section: '01',
    title: 'Consumer Behavior',
    days: 'M',
    startTime: '1:00 PM',
    endTime: '2:15 PM',
    enrollmentCap: '40',
    mode: 'Hybrid Sync',
    guestLectureFit: 'High',
  ),
  CourseScheduleItem(
    instructor: 'Olga Di Franco',
    course: 'IBM 4112',
    section: '02',
    title: 'Consumer Behavior',
    days: 'M',
    startTime: '2:30 PM',
    endTime: '3:45 PM',
    enrollmentCap: '40',
    mode: 'Hybrid Sync',
    guestLectureFit: 'High',
  ),
  CourseScheduleItem(
    instructor: 'L. Lin Ong',
    course: 'IBM 4112',
    section: '04',
    title: 'Consumer Behavior',
    days: 'T',
    startTime: '8:30 AM',
    endTime: '9:45 AM',
    enrollmentCap: '30',
    mode: 'Hybrid Sync',
    guestLectureFit: 'High',
  ),
  CourseScheduleItem(
    instructor: 'Elif Ozkaya',
    course: 'IBM 3072',
    section: '01',
    title: 'Promotional Strategies',
    days: 'T TH',
    startTime: '4:00 PM',
    endTime: '5:15 PM',
    enrollmentCap: '30',
    mode: 'Face-to-Face',
    guestLectureFit: 'Medium',
  ),
  CourseScheduleItem(
    instructor: 'Elif Ozkaya',
    course: 'IBM 3072',
    section: '04',
    title: 'Promotional Strategies',
    days: 'T TH',
    startTime: '2:30 PM',
    endTime: '3:45 PM',
    enrollmentCap: '30',
    mode: 'Face-to-Face',
    guestLectureFit: 'Medium',
  ),
  CourseScheduleItem(
    instructor: 'Paul-Long Lee',
    course: 'IBM 3072',
    section: '02',
    title: 'Promotional Strategies',
    days: 'M W',
    startTime: '7:00 PM',
    endTime: '8:15 PM',
    enrollmentCap: '30',
    mode: 'Face-to-Face',
    guestLectureFit: 'Medium',
  ),
  CourseScheduleItem(
    instructor: 'Elif Ozkaya',
    course: 'IBM 4032',
    section: '01',
    title: 'E-marketing',
    days: 'T TH',
    startTime: '10:00 AM',
    endTime: '11:15 AM',
    enrollmentCap: '30',
    mode: 'Face-to-Face',
    guestLectureFit: 'Medium',
  ),
  CourseScheduleItem(
    instructor: 'Wendy Bendoni',
    course: 'IBM 4032',
    section: '02',
    title: 'E-marketing',
    days: 'W',
    startTime: '8:30 AM',
    endTime: '9:45 AM',
    enrollmentCap: '30',
    mode: 'Hybrid Async',
    guestLectureFit: 'Medium',
  ),
  CourseScheduleItem(
    instructor: 'Lydia Chen Shah',
    course: 'IBM 4032',
    section: '03',
    title: 'E-marketing',
    days: 'M',
    startTime: '2:30 PM',
    endTime: '3:45 PM',
    enrollmentCap: '30',
    mode: 'Hybrid Sync',
    guestLectureFit: 'Medium',
  ),
  CourseScheduleItem(
    instructor: 'Lydia Chen Shah',
    course: 'IBM 3262S',
    section: '01',
    title: 'Interactive Marketing Svc Lrng',
    days: 'T',
    startTime: '1:00 PM',
    endTime: '2:15 PM',
    enrollmentCap: '30',
    mode: 'Hybrid Sync',
    guestLectureFit: 'Medium',
  ),
  CourseScheduleItem(
    instructor: 'Lydia Chen Shah',
    course: 'IBM 3262S',
    section: '02',
    title: 'Interactive Marketing Svc Lrng',
    days: 'M',
    startTime: '1:00 PM',
    endTime: '2:15 PM',
    enrollmentCap: '30',
    mode: 'Hybrid Sync',
    guestLectureFit: 'Medium',
  ),
  CourseScheduleItem(
    instructor: 'Lydia Chen Shah',
    course: 'GBA 6400S',
    section: '01',
    title: 'Sustainable Dvlpmnt Mkt Svc Lr',
    days: 'T',
    startTime: '7:00 PM',
    endTime: '9:45 PM',
    enrollmentCap: '30',
    mode: 'Hybrid Async',
    guestLectureFit: 'Medium',
  ),
  CourseScheduleItem(
    instructor: 'In Hye Kang',
    course: 'IBM 3282',
    section: '01',
    title: 'Social Media Marketing',
    days: 'M',
    startTime: '10:00 AM',
    endTime: '11:15 AM',
    enrollmentCap: '30',
    mode: 'Face-to-Face',
    guestLectureFit: 'Medium',
  ),
  CourseScheduleItem(
    instructor: 'Michael Becker',
    course: 'IBM 3292',
    section: '01',
    title: 'Mobile Marketing',
    days: 'T TH',
    startTime: '5:30 PM',
    endTime: '6:45 PM',
    enrollmentCap: '30',
    mode: 'Fully Sync',
    guestLectureFit: 'Medium',
  ),
  CourseScheduleItem(
    instructor: 'Megan Good',
    course: 'IBM 3062',
    section: '02',
    title: 'Professional Selling',
    days: 'T TH',
    startTime: '10:00 AM',
    endTime: '11:15 AM',
    enrollmentCap: '30',
    mode: 'Face-to-Face',
    guestLectureFit: 'Medium',
  ),
  CourseScheduleItem(
    instructor: 'Michael Assumma',
    course: 'IBM 4212',
    section: '01',
    title: 'Marketing Problems',
    days: 'T',
    startTime: '5:30 PM',
    endTime: '6:45 PM',
    enrollmentCap: '30',
    mode: 'Hybrid Sync',
    guestLectureFit: 'Medium',
  ),
  CourseScheduleItem(
    instructor: 'Jenny Feng',
    course: 'IBM 4212',
    section: '02',
    title: 'Marketing Problems',
    days: 'M',
    startTime: '5:30 PM',
    endTime: '6:45 PM',
    enrollmentCap: '35',
    mode: 'Hybrid Sync',
    guestLectureFit: 'Medium',
  ),
  CourseScheduleItem(
    instructor: 'Jenny Feng',
    course: 'IBM 4212',
    section: '03',
    title: 'Marketing Problems',
    days: 'M',
    startTime: '7:00 PM',
    endTime: '8:15 PM',
    enrollmentCap: '35',
    mode: 'Hybrid Sync',
    guestLectureFit: 'Medium',
  ),
  CourseScheduleItem(
    instructor: 'Neha Singh',
    course: 'IBM 4141',
    section: '01',
    title: 'International Marketing',
    days: 'M',
    startTime: '10:00 AM',
    endTime: '11:15 AM',
    enrollmentCap: '30',
    mode: 'Hybrid Sync',
    guestLectureFit: 'Medium',
  ),
  CourseScheduleItem(
    instructor: 'Ali Kowsari',
    course: 'IBM 4161',
    section: '02',
    title: 'International Exporting',
    days: 'T',
    startTime: '1:00 PM',
    endTime: '2:15 PM',
    enrollmentCap: '30',
    mode: 'Hybrid Sync',
    guestLectureFit: 'Low',
  ),
  CourseScheduleItem(
    instructor: 'Ali Kowsari',
    course: 'IBM 4291',
    section: '01',
    title: 'International Logistics',
    days: 'T',
    startTime: '2:30 PM',
    endTime: '3:45 PM',
    enrollmentCap: '30',
    mode: 'Hybrid Sync',
    guestLectureFit: 'Low',
  ),
  CourseScheduleItem(
    instructor: 'Fan Wang',
    course: 'IBM 4161',
    section: '01',
    title: 'International Exporting',
    days: 'M W',
    startTime: '2:30 PM',
    endTime: '3:45 PM',
    enrollmentCap: '30',
    mode: 'Face-to-Face',
    guestLectureFit: 'Low',
  ),
  CourseScheduleItem(
    instructor: 'Fan Wang',
    course: 'IBM 4801',
    section: '01',
    title: 'Intl Business Strategy',
    days: 'M W',
    startTime: '10:00 AM',
    endTime: '11:15 AM',
    enrollmentCap: '40',
    mode: 'Face-to-Face',
    guestLectureFit: 'Low',
  ),
  CourseScheduleItem(
    instructor: 'Olga Di Franco',
    course: 'IBM 3001',
    section: '01',
    title: 'Principles of Global Business',
    days: 'M',
    startTime: '5:30 PM',
    endTime: '6:45 PM',
    enrollmentCap: '30',
    mode: 'Hybrid Sync',
    guestLectureFit: 'Low',
  ),
  CourseScheduleItem(
    instructor: 'L. Lin Ong',
    course: 'IBM 3001',
    section: '02',
    title: 'Principles of Global Business',
    days: 'T',
    startTime: '10:00 AM',
    endTime: '11:15 AM',
    enrollmentCap: '30',
    mode: 'Hybrid Sync',
    guestLectureFit: 'Low',
  ),
  CourseScheduleItem(
    instructor: 'Maha Ghosn',
    course: 'IBM 3012',
    section: '07',
    title: 'Principles of Marketing Mgmt',
    days: 'M W',
    startTime: '5:30 PM',
    endTime: '6:45 PM',
    enrollmentCap: '77',
    mode: 'Face-to-Face',
    guestLectureFit: 'Low',
  ),
  CourseScheduleItem(
    instructor: 'Michael Assumma',
    course: 'IBM 3012',
    section: '05',
    title: 'Principles of Marketing Mgmt',
    days: 'TH',
    startTime: '7:00 PM',
    endTime: '9:45 PM',
    enrollmentCap: '40',
    mode: 'Face-to-Face',
    guestLectureFit: 'Low',
  ),
  CourseScheduleItem(
    instructor: 'Michael Assumma',
    course: 'IBM 3012',
    section: '06',
    title: 'Principles of Marketing Mgmt',
    days: 'T',
    startTime: '7:00 PM',
    endTime: '9:45 PM',
    enrollmentCap: '40',
    mode: 'Face-to-Face',
    guestLectureFit: 'Low',
  ),
];
