// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAZLcKDWaG6uh71a2iRMX4sil1WPbpDVzw',
    appId: '1:1062034930573:android:475bb386012fd6c634dbc4',
    messagingSenderId: '1062034930573',
    projectId: 'cpp-aihackathon',
    storageBucket: 'cpp-aihackathon.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDSRxiGM7i3giXmcBvXjQ5Eyoxoq7m6WcA',
    appId: '1:1062034930573:ios:89af7cb7823abfef34dbc4',
    messagingSenderId: '1062034930573',
    projectId: 'cpp-aihackathon',
    storageBucket: 'cpp-aihackathon.firebasestorage.app',
    iosBundleId: 'com.example.insightQuestMobile',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCP3HwYl0QUWr0-h63hlIrDe4EALxg5Brs',
    appId: '1:1062034930573:web:913ed2f6ae1a828f34dbc4',
    messagingSenderId: '1062034930573',
    projectId: 'cpp-aihackathon',
    authDomain: 'cpp-aihackathon.firebaseapp.com',
    storageBucket: 'cpp-aihackathon.firebasestorage.app',
    measurementId: 'G-R9CGS3SVSV',
  );

}